remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
title: SOF GUI Project Blog
author: Alex Brown
description: This blog will contain updates on the process of the SOF GUI GSoC Project.
